### ISSUE TITLE
Instalasi VOIP ID

### ISSUE THREAD

**Issue by sentabi** [antonraharja/book-voip-id#7]
Di Step 1: apa ngga perlu di revisi :D kalo orang install aplikasi ini di VPS (sebagian besar pake template) LAMP-nya ngga ikut terinstall. 
Sebenarnya tinggal install LAMP pake

```
apt-get install apache2 php5 mysql-server mysql-client
```

di step 10 juga perlu di revisi mending buat vhost baru daripada me-nggantikan isi /var/www/html mana tau ada data-data penting didalamnya. 

karena artikelnya pake bahasa inggris makanya saya buka issue aja buka pull request

**Comment by antonraharja** [comment]
sbnr nya kan sudah dijelaskan harus ada LAMP, tapi mungkin biar jelas ditambahkan aja info diatas.

di step 10 memang sengaja dicarikan yang mudah, implementasi sesungguhnya, optimasi2, hardening dll bukan bagian dari buku ini.

plus, server ini memang sebaiknya dedicated, kalo mau belajar pun sebaiknya demikian.

**Comment by sentabi** [comment]
bukan masalah hardening dan dedicated sih, tapi kemudahan user untuk instalasinya. 
Tapi kalo ini di close ya udah deh.

Thanks

**Comment by antonraharja** [comment]
ini ditutup otomatis oleh github saat commit perbaikan sesuai saran anda :)

untuk step 10 kalo memang ada cara yang lebih mudah dan coba beri contohnya, disini juga boleh. close pun kan tetap bisa posting. nanti saya pertimbangkan untuk commit lagi.

thanks,
anton

**Comment by sentabi** [comment]
// edited
